# Generated by Django 6.0.2 on 2026-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('basic_salary', models.FloatField()),
                ('hra', models.FloatField()),
                ('da', models.FloatField()),
                ('allowance', models.FloatField()),
                ('pf', models.FloatField()),
                ('esi', models.FloatField()),
            ],
        ),
    ]
