# Generated by Django 6.0.2 on 2026-02-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('leave_days', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employeedetails')),
            ],
        ),
    ]
