# Generated by Django 6.0.2 on 2026-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0002_leavedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
