# Generated by Django 6.0.2 on 2026-02-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_leavedetails_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavedetails',
            name='userid',
        ),
    ]
